<a href="https://colab.research.google.com/github/shahalaap/LEARN.PY/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [ ]:
#please provide your answer below this line.
from numpy import*
 
arr1 = array([
                [1,2,3,4,5,6,7,8,9]
 
            ])
 
arr2 = arr1.reshape(3,3)
 
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [2]:
#please provide your answer below this line.
import numpy as np
 
a = np.arange(1,17).reshape(4,4)
b = np.arange(18,34).reshape(4,4)
 
print(a)
print(b)
 
c = np.arange(1,17).reshape(2,8)
print(c)
 
d = np.arange(18,34).reshape(2,8)
print(d)
 
e = np.vstack((a,b))
print(e)
 
f = np.hstack((a,b))
print(f)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[18 19 20 21 22 23 24 25]
 [26 27 28 29 30 31 32 33]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]]
[[ 1  2  3  4 18 19 20 21]
 [ 5  6  7  8 22 23 24 25]
 [ 9 10 11 12 26 27 28 29]
 [13 14 15 16 30 31 32 33]]
