<a href="https://colab.research.google.com/github/shahalaap/LEARN.PY/blob/main/TASK_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array with elements ranging from 0-15. And find the trace of the array.

In [7]:
#please type your answer below this line
import numpy as np
 
a = np.arange(0,16).reshape(4,4)
a.trace()

30

2. Create a matrix with elements [6,1,1],[4,-2,5],[2,8,7].Now find the inverse this matrix.

In [8]:
#please type your answer below this line.
import numpy as np
 
A = np.array([[6, 1, 1],
             [4, -2, 5],
             [2, 8, 7]])
 
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


3. Create an 3x3 array with elements ranging from 0-8. And find the norm this array.

In [11]:
#please type your answer below this line.
import numpy as np
 
a = np.arange(0,9).reshape(3,3)
 
print(np.linalg.norm(a))

14.2828568570857


4. Create a 4x4 array whose value ranging from 0-15.And find the eigenvalues and eigenvectors of this array.

In [18]:
#please type your answer below this line.
import numpy as np
 
a = np.arange(0,16).reshape(4,4)
print(a)
 
x, y = np.linalg.eig(a)
 
print("Printing the Eigen value of the given square array:\n", x)
print("Printing the eigenvectors of the given square array:\n", y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Printing the Eigen value of the given square array:
 [ 3.24642492e+01 -2.46424920e+00  2.55670932e-15 -1.93389056e-16]
Printing the eigenvectors of the given square array:
 [[-0.11417645  0.7327781  -0.54471271  0.09683789]
 [-0.3300046   0.28974835  0.76902356  0.27269982]
 [-0.54583275 -0.15328139  0.09609099 -0.8359133 ]
 [-0.76166089 -0.59631113 -0.32040185  0.46637559]]
