<a href="https://colab.research.google.com/github/shahalaap/LEARN.PY/blob/main/TASK_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create two arrays, one containing elements [1,2], [3,4] and another containing elements [8,18] Now find the solution for this linear equation.

In [27]:
#please type your answer below this line.
import numpy as np
a = np.array([[1,2],[3,4]])
 
b = np.array([8,18])
 
np.linalg.solve(a,b)

array([2., 3.])

2. Create an array containing elements [2, 3, 4]. Now find the sin,cos,tan values of this array elements.

In [5]:
#please type your answer below this line.
import numpy as np
import math
a = np.array([2,3,4])
 
sin_a = np.sin(a)
print(sin_a)
 
cos_a = np.cos(a)
print(cos_a)
 
tan_a = np.sin(a)/np.cos(a)
print(tan_a)

[ 0.90929743  0.14112001 -0.7568025 ]
[-0.41614684 -0.9899925  -0.65364362]
[-2.18503986 -0.14254654  1.15782128]


3. Given b=[5,6], then find,

  a) 2sinb
  b) 2cos3b
  c) 4tan2b

In [26]:
#please type your answer below this line.
import numpy as np
import math
b = np.array([5,6])
 
print("2sinb")
x = np.sin(b)
x1 = 2*x
print(x1)
 
print("2cos3b")
y = 3*b
y1 = np.cos(y)
y2 = 2*y1
print(y2)
 
print("4tan2b")
z = 2*b
z1 = np.sin(z)/np.cos(z)
z2 = 4*z1
print(z2)

2sinb
[-1.91784855 -0.558831  ]
2cos3b
[-1.51937583  1.32063342]
4tan2b
[ 2.59344331 -2.54343971]
